name: Lint docs
on: [push, pull_request]
jobs:
  check_md:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Lint markdown files (markdownlint)
        uses: articulate/actions-markdownlint@v1
        with:
          config: .markdownlint.json
          files: '.github/**/*.md'
